### ISSUE TITLE
Buttons feature request

### ISSUE THREAD

**Issue by danvim** [bevacqua/woofmark#11]
I have some feature requests.
1. Can you add an option to let the buttons render on top of the textarea?
2. Can the buttons including custom ones get arranged for display? For example, bring the Heading buttons left, next to italic?

**Comment by derhuerst** [comment]
@vimxts about 1: I think this is an edge-case that shouldn't affect the size or performance of woofmark. Maybe this is possible with clever external CSS?

**Comment by danvim** [comment]
@derhuerst I can do it with CSS and of course JavaScript too, but wouldn't it be better if woofmark includes the option to prepend the buttons before the textarea?

Also, I haven't been able to do it with CSS, maybe because I'm not clever enough:
1. I want `.wk-commands` and `.wk-switchboard` to float left so that they float in one line.
2. They have to be positioned on top of the textarea.
3. I should be able to add new command buttons to the sets and still be able to see everything.

I would use JS for this actions, I suppose it is a get around to the issue, I can even do it for the 2.

But I wish woofmark can include these helpful options while generating the editor, so a bigger liberty to styling can be achieved.

They other thing I would like to request is that woofmark should wrap `.wk-commands` and `.wk-switchboard` within a `<div>` upon generation.

**Comment by bevacqua** [comment]
I'm sorry but I'm not interested in adding this to core
