### ISSUE TITLE
Some questions :)

### ISSUE THREAD

**Issue by shiren** [bevacqua/woofmark#12]
![2015-06-16 4 33 33](https://cloud.githubusercontent.com/assets/389021/8178008/74470c16-1445-11e5-84d5-86ef90e92120.png)

I need some functions as below.

1) the way to apply widget like facebook's mention ui 
2) text highlights in textarea (you can see a automatically highlighted name when you mention your friend’s name with “@“ in Facebook)

Does woofmark provide a way to do them?
Or do you have any plan to provide?

thank!

**Comment by bevacqua** [comment]
The first you can already do using [insignia](https://github.com/bevacqua/insignia). The second you can easily do by restricting the editor to WYSIWYG mode only and highlighting links via CSS.
