### ISSUE TITLE
Enhancement Request: Set the value of the editor using markdown

### ISSUE THREAD

**Issue by samhagman** [bevacqua/woofmark#15]
The way I picture this working is a function being added to the editor object like `editor.setValue(markdownString)`. 

This would internally check `editor.mode` and then either just insert the markdownString into the editor (if in markdown mode) **or** run `editor.parseMarkdown(markdownString)` and then either render or insert the resulting HTML string into the editor (if in html or wysiwyg mode respectively).

It also wouldn't hurt to make this an option to pass into the `woofmark()` function with a name like `option.initialValue` or something.

_P.S. Thanks for this great extensible library._

**Comment by tsileo** [comment]
I use a command that update the chunk with the new value:

``` js
var newString = 'new **markdown** value';
editor.runCommand(function(chunks, mode) {
  chunks.after='';
  if (mode == 'html') {
    chunks.before = editor.parseMarkdown(newString);
  } else {
    chunks.before = newString;
  }
});
```

**Comment by jywarren** [comment]
Perhaps this should be integrated into the `editor.value()` method -- that way `value('new **markdown** value')` could be used as a setter and a getter. I would be happy to open a pull request for this as it seems a very common thing to want to do and an easy addition.

**Comment by bevacqua** [comment]
Sounds good to me

**Comment by jywarren** [comment]
I seemed to be able to make a simpler fix which added a setter ability to the `value()` method; see #27.

**Comment by samhagman** [comment]
@jywarren Awesome, I'll close this when that gets merged, thank you for your efforts!

**Comment by bevacqua** [comment]
`4.1.0`
