### ISSUE TITLE
*ashamed* I don't get the original textarea to sync with woofmark

### ISSUE THREAD

**Issue by CanRau** [bevacqua/woofmark#22]
Hola, I just stumbled over woofmark last night, and so far I like it.

But I can't figure out how to sync those. I mean, when submitting the form, nothing get posted..?
This is my js to init woofmark..

```
var rte = document.querySelector('.rich-text');
    woofmark(rte, {
        parseMarkdown: megamark,
        parseHTML: domador,
        defaultMode: 'wysiwyg'
    });
```

Use case, I want to provide an easy (wysiwyg) forum input but behind the scenes everything should be markdown. Do I need parseMarkdown and parseHTML for this?
Maybe I should learn more vanilla-js..

Saludos, Can

**Comment by bevacqua** [comment]
you need to read from `woofmark`. Do `var foo = woofmark(rte, ...)` and then `foo.value()` will always return markdown

**Comment by CanRau** [comment]
Thank you :)
