### ISSUE TITLE
Code blocks

### ISSUE THREAD

**Issue by cdekok** [bevacqua/woofmark#3]
It doesn seem to work for code blocks is this supposed to support the full markdown spec http://commonmark.org?

e.g. for example

```php
<?=´hello´?>
```

**Comment by bevacqua** [comment]
The issue here is `insane` is getting rid of "unwanted" tags even in code blocks, while it should probably ignore code blocks altogether.

**Comment by bevacqua** [comment]
Can you please post this over to `insane`?
