### ISSUE TITLE
image upload response needs to be parsed into JSON? 

### ISSUE THREAD

**Issue by jywarren** [bevacqua/woofmark#30]
I'm responding (from Rails) to an image upload, and when I send a response back it's parsed as a string, not JSON, oddly. The headers seem right:

```
Cache-Control:max-age=0, private, must-revalidate
Connection:keep-alive
Content-Encoding:gzip
Content-Type:application/json; charset=utf-8
Date:Fri, 03 Jun 2016 18:14:26 GMT
ETag:W/"366c2e915957fbb3688349173c85b656"
Server:nginx/1.8.1 + Phusion Passenger 5.0.26
Set-Cookie:_session_id=546ca71df6549ce20171d258b9616027; path=/; HttpOnly
Status:200 OK
Transfer-Encoding:chunked
X-Powered-By:Phusion Passenger 5.0.26
X-Request-Id:39752ef745d8261da5eee350caa554a3
X-Runtime:5.814758
X-UA-Compatible:IE=Edge
```

And the response body is:

``` json
{"id":29,"url":"/system/images/photos/000/000/029/large/batman.gif","filename":"batman.gif","href":"/system/images/photos/000/000/029/large/batman.gif","title":"batman.gif"}
```

However, I had to add the following to line 180 of Woofmark's `prompts/prompt.js` to get `body.href` to return anything: 

``` js
body = JSON.parse(body);
```

Do you think I'm doing something wrong in encoding my server response, and/or would adding an extra check and ability to parse into JSON be a useful extension to Woofmark's abilities? 

Thanks!

**Comment by jywarren** [comment]
Alternatively, the ability to pass an `onResponse()` or `after()` method in the `images` options object, to enable custom response parsing?

**Comment by bevacqua** [comment]
This changed quite a bit actually

**Comment by bevacqua** [comment]
See [`bureaucracy`](https://github.com/bevacqua/bureaucracy)

**Comment by jywarren** [comment]
Oh, cool -- do you mean potentially to use bureaucracy in `woofmark` code or just in my application code? Thanks!

**Comment by bevacqua** [comment]
Woofmark already uses bureaucracy now. That's what I meant

**Comment by jywarren** [comment]
Awesome, thanks!

**Comment by jywarren** [comment]
Closing this now for an issue in `bureaucracy`: https://github.com/bevacqua/bureaucracy/issues/1

Thanks!
