### ISSUE TITLE
GFM Tables do not work properly

### ISSUE THREAD

**Issue by styfle** [bevacqua/woofmark#4]
First of all, woofmark looks awesome! I think this would work great with our app.

I found a bug with tables however. Here are the steps to reproduce on the demo page http://bevacqua.github.io/woofmark/
#### Click markdown icon and paste the following

``` markdown
| col1 | col2 | col3 |
|------|------|------|
| foo  | bar  | baz  |
| food | bars | bats |
```
#### Click wysiwyg icon and you'll see a table (woohoo!) but without borders (boo)

| col1 | col2 | col3 |
| --- | --- | --- |
| foo | bar | baz |
| food | bars | bats |
#### Click html icon and you'll see proper html table (woohoo!)

``` html
<table>
<thead>
<tr><th>col1</th><th>col2</th><th>col3</th></tr>
</thead>
<tbody>
<tr><td>foo</td><td>bar</td><td>baz</td></tr>
<tr><td>food</td><td>bars</td><td>bats</td></tr>
</tbody>
</table>
```
#### Now click markdown icon and you'll get paragraphs?? (oops)

```
col1col2col3

foobarbaz

foodbarsbats
```

I'm assuming the html -> markdown doesn't support tables yet?

**Comment by styfle** [comment]
From the docs this sounds like the issue might be in [domador](https://github.com/bevacqua/domador) maybe.

**Comment by bevacqua** [comment]
Yeah, please report this on domador. Thanks

**Comment by jywarren** [comment]
Closed in domador: https://github.com/bevacqua/domador/issues/1 but I'm still seeing tables get munged when I go HTML > Markdown > HTML > Markdown (probably only the last 3 are necessary). Is this fix already integrated; i.e. is woofmark now depending on the fixed domador? 

Thanks, woofmark is awesome!
