### ISSUE TITLE
can we have drag/drop support for images

### ISSUE THREAD

**Issue by vviikk** [bevacqua/woofmark#5]
i.e. dropped image is converted to base64 encoding and embedded as dataURI? @let4be

**Comment by bevacqua** [comment]
There is support for this but just dropping images in the image dialog works. I'd definitely merge a pull request for dropping images or attachments on the editor itself

**Comment by vviikk** [comment]
Thanks. We're the guys over at Lavaboom. We're trying to scout for the best wysiwyg editor out there with markdown support. It's for our email client.

https://github.com/lavab/web/

If we do decide to go with woofmark I will send you a message. Thanks!

**Comment by bevacqua** [comment]
This is coming.

**Comment by bevacqua** [comment]
Deployed as `3.0.0`, enabled by default, if you've set up attachment or image uploads, then it'll work seamlessly. When something is dropped onto the input, the dialog will be opened and the upload will be processed. The dialog is still used because it's a crutch to display validation messaging and whatnot.

**Comment by bevacqua** [comment]
Demo:

<img width="1440" alt="screen shot 2015-07-21 at 18 30 43" src="https://cloud.githubusercontent.com/assets/934293/8813053/9d2388c4-2fd6-11e5-888f-83060a819a9e.png">

**Comment by vviikk** [comment]
nice! @let4be!

**Comment by jywarren** [comment]
Noting a follow-up to try to intercept data-url images that are inserted that would overload databases if stored in the midst of a text post (we've seen this happen rarely on our system): #38 

Thanks!

**Comment by jywarren** [comment]
Oops, wrong one -- #69 !
