### ISSUE TITLE
Provide tick list function

### ISSUE THREAD

**Issue by spoorun** [bevacqua/woofmark#53]
It would be highly useful to tick list (checklist), in addition to the existing bulleted and numbered lists.
This list would enable items listed in it to marked as done, or not done, by virtue of a tick (check mark).

**Comment by bevacqua** [comment]
This simply renders compiled markdown and allows editing of it, but if you want custom Markdown compilation features that'll belong with a markdown parser like `markdown-it`. I'm sure there's a plugin for what you're asking.
