### ISSUE TITLE
Package woofmark not found

### ISSUE THREAD

**Issue by CorentinDodon** [bevacqua/woofmark#6]
I wanted to add woofmark to my project with Bower but when i tried
->
'Bower install woofmark --save' return Package woofmark not found

Did you forgot something or is it just a random bug ?

**Comment by bevacqua** [comment]
Fixed. Thanks!

**Comment by derhuerst** [comment]
For documentation purposes, it is helpful to, at some point in the future, be able to get to know _how_ you fixed the bug; So it would be great if you could reference the commit, pull request or issue number.

**Comment by bevacqua** [comment]
There's none of that. I just did:

``` shell
bower register woofmark https://github.com/bevacqua/woofmark.git
```
