### ISSUE TITLE
Is there a way to access the InputHistory within the source?

### ISSUE THREAD

**Issue by danvim** [bevacqua/woofmark#7]
I examined the source of the code. I'm sorry I am not familiar with the node styled javascript. I would like to add buttons for the functions for redoing and undoing history. Is that something doable?

**Comment by bevacqua** [comment]
We could consider exposing the `history` instance on the public API, or maybe a subset of its API (the methods that make sense to expose, like `undo`, `redo`, `canUndo`, `canRedo`, and `reset`.
