### ISSUE TITLE
Uncaught Error: woofmark demands <textarea> elements to have no siblings

### ISSUE THREAD

**Issue by h3rb** [bevacqua/woofmark#70]
What pray tell does this mean?!?!

**Comment by kakra** [comment]
This message also puzzled me at first glance. You need to wrap the textarea in a div so the div has no other children than the textarea - which means the textarea would have no siblings. It would be easier to understand if the error message would say "woofmark demands the <textarea> to be the only child of its parent element".

**Comment by npyl** [comment]
> This message also puzzled me at first glance. You need to wrap the textarea in a div so the div has no other children than the textarea - which means the textarea would have no siblings. It would be easier to understand if the error message would say "woofmark demands the <textarea> to be the only child of its parent element".

This fixes it! Thanks.
